# naopontan pukiwiki の環境
# MEMO: pukiwiki は mysql 不要
# Amazon Linux 2018.03-release
# yum update -y は各自で
package 'httpd24' do
  action :install
end

# https でつながるようにする。 /etc/httpd/conf.d/ssl.conf が出来上がる
package 'mod24_ssl' do
  action :install
end

directory "/home/ec2-user/public_html" do
  owner "ec2-user"
  mode "0775"
end

file "/etc/httpd/conf/httpd.conf" do
  action :edit
  block do |content|
    content.gsub!(/^Listen 80$/, "#Listen 80")
    content.gsub!(/^DocumentRoot .*/, 'DocumentRoot "/home/ec2-user/public_html"')
  end
end

file "/etc/ssh/sshd_config" do
  action :edit
  block do |content|
    content.gsub!(/^Listen 80$/, "#Listen 80")
  end
end

# yum -y remove php70-*
%w[php56 php56-devel php56-mbstring php56-mcrypt php56-mysqlnd php56-pdo].each do |pkg|
  package pkg do
    action :install
  end
end

=begin
アクセスを許可するクライアントIPを設定するには Webインタフェースは用意されていないので、
自分で F/W の設定をする必要がある。

自宅は IPv6 でつなげているが、 IPv4 だと以下のIPだ!?
99.99.999.0/32
(EC2 のセキュリティグループでルールの追加時に「マイ IP」を選ぶと自動で出してくれるので、それで確認した)

 [root@ip-172-26-0-130 ~]# iptables -A INPUT -p tcp -s 99.99.999.0/32
--dport 443 -j ACCEPT
 [root@ip-172-26-0-130 ~]# iptables -A INPUT -p tcp --dport 443 -j DROP
 [root@ip-172-26-0-130 ~]# /etc/init.d/iptables save
 iptables: Saving firewall rules to /etc/sysconfig/iptables:[  OK  ]
 [root@ip-172-26-0-130 ~]# cat /etc/sysconfig/iptables
 # Generated by iptables-save v1.4.18 on Sun Nov 18 14:29:33 2018
 *filter
 :INPUT ACCEPT [63:4464]
 :FORWARD ACCEPT [0:0]
 :OUTPUT ACCEPT [73:25970]
 -A INPUT -s 99.99.999.0/32 -p tcp -m tcp --dport 443 -j ACCEPT
 -A INPUT -p tcp -m tcp --dport 443 -j DROP
 COMMIT
 # Completed on Sun Nov 18 14:29:33 2018
 [root@ip-172-26-0-130 ~]#

# あと、厳重にするなら Webサーバでもアクセス制限かける
# .htaccess とか。
=end

# phpの動作確認
# [root@ip-172-26-0-130 html]# pwd
# /var/www/html
# [root@ip-172-26-0-130 html]# cat index.php
# <?php
#   phpinfo();
# ?>
# [root@ip-172-26-0-130 html]#

execute "chmod 0755 ~ec2-user"

remote_file "/home/ec2-user/public_html/index.php" do
  owner "ec2-user"
  mode "0755"
end

# start しない!?
service 'httpd' do
  action [:enable, :start]
end
